name: Download from GDrive to Release V3

on:
  workflow_dispatch:
    inputs:
      gdrive_id:
        description: 'Google Drive ID'
        required: true
      is_folder:
        description: 'is_folder'
        required: true
        default: 'false'

jobs:
  download_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install gdown
      run: pip install gdown

    - name: Download from Google Drive
      run: |
        mkdir downloads
        cd downloads
        if [ "${{ github.event.inputs.is_folder }}" = "true" ]; then
          gdown --folder --id "${{ github.event.inputs.gdrive_id }}"
        else
          gdown --id "${{ github.event.inputs.gdrive_id }}"
        fi
        cd ..
        
        # 将下载的文件打包
        zip -r0 models.zip downloads/
        
        # 核心步骤：将 11GB 的大文件切分为多个 1.9GB 的小切片，绕过 GitHub 的 2GB 限制
        split -b 1900M models.zip "models.zip.part"
        
        # 删除原始大文件，腾出硬盘空间
        rm models.zip

    - name: Create Release and Upload
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: models.zip.part*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
